var searchData=
[
  ['strong_0',['strong',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'&lt;strong&gt;1. Prérequis&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md5',1,'&lt;strong&gt;2. Cloner le repository&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md7',1,'&lt;strong&gt;3. Configuration initiale&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md8',1,'&lt;strong&gt;3.1 Configurer votre identité Git&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md9',1,'&lt;strong&gt;3.2 Vérifier le lien avec le repository GitHub&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md11',1,'&lt;strong&gt;4. Travailler sur le projet&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md12',1,'&lt;strong&gt;4.1 Mettre à jour votre copie locale&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md13',1,'&lt;strong&gt;4.2 Ajouter de nouvelles modifications&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md14',1,'&lt;strong&gt;4.3 Envoyer les modifications sur GitHub&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md16',1,'&lt;strong&gt;5. Créer et utiliser des branches&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md18',1,'&lt;strong&gt;6. Résoudre les conflits&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md20',1,'&lt;strong&gt;7. Récapitulatif des commandes utiles&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md22',1,'&lt;strong&gt;8. En cas de problème&lt;/strong&gt;'],['../md__r_e_a_d_m_e.html#autotoc_md1',1,'&lt;strong&gt;Instructions pour travailler avec le repository&lt;/strong&gt;']]],
  ['strong_201_20prérequis_20strong_1',['&lt;strong&gt;1. Prérequis&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['strong_202_20cloner_20le_20repository_20strong_2',['&lt;strong&gt;2. Cloner le repository&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['strong_203_201_20configurer_20votre_20identité_20git_20strong_3',['&lt;strong&gt;3.1 Configurer votre identité Git&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['strong_203_202_20vérifier_20le_20lien_20avec_20le_20repository_20github_20strong_4',['&lt;strong&gt;3.2 Vérifier le lien avec le repository GitHub&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['strong_203_20configuration_20initiale_20strong_5',['&lt;strong&gt;3. Configuration initiale&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['strong_204_201_20mettre_20à_20jour_20votre_20copie_20locale_20strong_6',['&lt;strong&gt;4.1 Mettre à jour votre copie locale&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['strong_204_202_20ajouter_20de_20nouvelles_20modifications_20strong_7',['&lt;strong&gt;4.2 Ajouter de nouvelles modifications&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['strong_204_203_20envoyer_20les_20modifications_20sur_20github_20strong_8',['&lt;strong&gt;4.3 Envoyer les modifications sur GitHub&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['strong_204_20travailler_20sur_20le_20projet_20strong_9',['&lt;strong&gt;4. Travailler sur le projet&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['strong_205_20créer_20et_20utiliser_20des_20branches_20strong_10',['&lt;strong&gt;5. Créer et utiliser des branches&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['strong_206_20résoudre_20les_20conflits_20strong_11',['&lt;strong&gt;6. Résoudre les conflits&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['strong_207_20récapitulatif_20des_20commandes_20utiles_20strong_12',['&lt;strong&gt;7. Récapitulatif des commandes utiles&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md20',1,'']]],
  ['strong_208_20en_20cas_20de_20problème_20strong_13',['&lt;strong&gt;8. En cas de problème&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md22',1,'']]],
  ['strong_20instructions_20pour_20travailler_20avec_20le_20repository_20strong_14',['&lt;strong&gt;Instructions pour travailler avec le repository&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['sur_20github_20strong_15',['&lt;strong&gt;4.3 Envoyer les modifications sur GitHub&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['sur_20le_20projet_20strong_16',['&lt;strong&gt;4. Travailler sur le projet&lt;/strong&gt;',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]]
];
